steps:
  - id: docker_buildx
    name: docker:20.10
    args:
      - build
      - --target=docker
      - --build-arg=DOCKER_VERSION=${_DOCKER_VERSION}
      - --build-arg=BUILDX_DIGEST=${_BUILDX_DIGEST}
      - --tag=docker-buildx:cloudbuild
      - --file=hack/dockerfiles/buildx.dockerfile
      - hack/dockerfiles
    env:
      - "DOCKER_BUILDKIT=1"
    waitFor:
      - "-"

  - id: bootstrap_buildx
    name: docker-buildx:cloudbuild
    args:
      - buildx
      - create
      - --bootstrap
      - --name=cloudbuild
      - --driver=docker-container
      - --driver-opt=image=moby/buildkit:nightly
      - --driver-opt=network=cloudbuild
      - --use
    waitFor:
      - "docker_buildx"

  - id: protoc-builder
    name: docker-buildx:cloudbuild
    args:
      - buildx
      - build
      - --target=protoc-builder
      - --build-arg=BUILDKIT_INLINE_CACHE=1
      - --build-arg=PROTOC_VERSION=${_PROTOC_VERSION}
      - --build-arg=GOLANG_VERSION=${_GOLANG_VERSION}
      - --build-arg=ALPINE_VERSION=${_ALPINE_VERSION}
      - --cache-from=type=registry,ref=gcr.io/$PROJECT_ID/protoc/protoc-builder:cloudbuild_cache
      - --output=type=image,name=gcr.io/$PROJECT_ID/protoc/protoc-builder:cloudbuild_cache,push=true
      - .
    waitFor:
      - "bootstrap_buildx"

  - id: protoc
    name: docker-buildx:cloudbuild
    args:
      - buildx
      - build
      - --target=protoc
      - --build-arg=PROTOC_VERSION=${_PROTOC_VERSION}
      - --build-arg=GOLANG_VERSION=${_GOLANG_VERSION}
      - --build-arg=ALPINE_VERSION=${_ALPINE_VERSION}
      - --tag=gcr.io/$PROJECT_ID/protoc/protoc:${_PROTOC_VERSION}
      - --load
      - .
    waitFor:
      - "protoc-builder"

  - id: protoc-debug
    name: docker-buildx:cloudbuild
    args:
      - buildx
      - build
      - --target=protoc-debug
      - --build-arg=PROTOC_VERSION=${_PROTOC_VERSION}
      - --build-arg=GOLANG_VERSION=${_GOLANG_VERSION}
      - --build-arg=ALPINE_VERSION=${_ALPINE_VERSION}
      - --tag=gcr.io/$PROJECT_ID/protoc/protoc:${_PROTOC_VERSION}-debug
      - --load
      - .
    waitFor:
      - "protoc-builder"

  - id: golang-builder
    name: docker-buildx:cloudbuild
    args:
      - buildx
      - build
      - --target=golang-builder
      - --build-arg=BUILDKIT_INLINE_CACHE=1
      - --build-arg=PROTOC_VERSION=${_PROTOC_VERSION}
      - --build-arg=GOLANG_VERSION=${_GOLANG_VERSION}
      - --build-arg=ALPINE_VERSION=${_ALPINE_VERSION}
      - --build-arg=PROTOC_GEN_GO_VERSION=${_PROTOC_GEN_GO_VERSION}
      - --build-arg=PROTOC_GEN_GO_GRPC_VERSION=${_PROTOC_GEN_GO_GRPC_VERSION}
      - --cache-from=type=registry,ref=gcr.io/$PROJECT_ID/protoc/golang-builder:cloudbuild_cache
      - --output=type=image,name=gcr.io/$PROJECT_ID/protoc/golang-builder:cloudbuild_cache,push=true
      - .
    waitFor:
      - "protoc"
      - "protoc-debug"

  - id: golang
    name: docker-buildx:cloudbuild
    args:
      - buildx
      - build
      - --target=golang
      - --build-arg=PROTOC_VERSION=${_PROTOC_VERSION}
      - --build-arg=GOLANG_VERSION=${_GOLANG_VERSION}
      - --build-arg=ALPINE_VERSION=${_ALPINE_VERSION}
      - --build-arg=PROTOC_GEN_GO_VERSION=${_PROTOC_GEN_GO_VERSION}
      - --build-arg=PROTOC_GEN_GO_GRPC_VERSION=${_PROTOC_GEN_GO_GRPC_VERSION}
      - --tag="gcr.io/$PROJECT_ID/protoc/golang:${_PR_NUMBER:-${_PROTOC_VERSION}-${_GOLANG_VERSION}}"
      - --load
      - .
    waitFor:
      - "golang-builder"

  - id: golang-debug
    name: docker-buildx:cloudbuild
    args:
      - buildx
      - build
      - --target=golang-debug
      - --build-arg=PROTOC_VERSION=${_PROTOC_VERSION}
      - --build-arg=GOLANG_VERSION=${_GOLANG_VERSION}
      - --build-arg=ALPINE_VERSION=${_ALPINE_VERSION}
      - --build-arg=PROTOC_GEN_GO_VERSION=${_PROTOC_GEN_GO_VERSION}
      - --build-arg=PROTOC_GEN_GO_GRPC_VERSION=${_PROTOC_GEN_GO_GRPC_VERSION}
      - --tag="gcr.io/$PROJECT_ID/protoc/golang:${_PR_NUMBER:-${_PROTOC_VERSION}-${_GOLANG_VERSION}}-debug"
      - --load
      - .
    waitFor:
      - "golang-builder"

substitutions:
  _DOCKER_VERSION: "20.10"
  _BUILDX_DIGEST: "2ec838c5f74e1cdd5e6ea4e789c0c0f5573807550b50b2ddc6deb2c2033a286b"  # https://github.com/docker/buildx/tree/084b6c0a95ce, https://github.com/docker/buildx/runs/3947339794
  _PROTOC_VERSION: "3.19.0"  # https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.0
  _GOLANG_VERSION: "1.17"
  _ALPINE_VERSION: "3.14"
  _PROTOC_GEN_GO_VERSION: "v1.27.1"  # https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.27.1
  _PROTOC_GEN_GO_GRPC_VERSION: "9c668aeab869"  # https://github.com/grpc/grpc-go/tree/9c668aeab869

# images:
#   - "gcr.io/$PROJECT_ID/protoc/protoc:${_PR_NUMBER:-${_PROTOC_VERSION}}"
#   - "gcr.io/$PROJECT_ID/protoc/protoc:${_PR_NUMBER:-${_PROTOC_VERSION}}-debug"
#   - "gcr.io/$PROJECT_ID/protoc/golang:${_PR_NUMBER:-${_PROTOC_VERSION}-${_GOLANG_VERSION}}"
#   - "gcr.io/$PROJECT_ID/protoc/golang:${_PR_NUMBER:-${_PROTOC_VERSION}-${_GOLANG_VERSION}}-debug"

tags:
  - "protoc.protoc"
  - "protoc.golang"

timeout: 900s  # 15min
